debug: true
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: auth-service-route
            uri: lb://AUTH-SERVICE
            predicates:
              - Path=/api/auth/**
              - Method=POST,OPTIONS,GET,DELETE,UPDATE
          - id: hospital-service-route

            uri: lb://HOSPITAL-SERVICE
            predicates:
              - Path=/api/hms/**
              - Method=GET,POST,OPTIONS,PUT
          - id: appointment-service-route
            uri: lb://APPOINTMENT-SERVICE
            predicates:
              - Path=/api/appointment/**
              - Method=POST,OPTIONS
          - id: patient-service-route
            uri: lb://PATIENT-SERVICE
            predicates:
              - Path=/api/patient/**
              - Method=POST,OPTIONS
          - id: billing-service-route
            uri: lb://BILLING-SERVICE
            predicates:
              - Path=/api/billing/**
              - Method=POST,OPTIONS

server:
  port: 6969
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA-SERVER:localhost}:8761/eureka